name: pybenford
# channels priority
# conda-forge has the highest priority
channels:
  - defaults
  - conda-forge
dependencies:
  # pybenford
  - pip
  - pip:
    - -r file:../requirements.txt
    - sphinx-book-theme
  # Jupyter lab and visualization
  - jupyterlab
  - matplotlib
  # Tests
  - pytest
  # Lint
  - pylint
  - pycodestyle
  - pydocstyle
  # Packaging
  - python-build
  - twine
  - bump2version
  # Documentation
  - sphinx
  - nbsphinx
  - myst-parser